name: quran
description: "Coran"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.0 # Mis à jour pour plus de stabilité avec sqflite

dependencies:
  flutter:
    sdk: flutter
  archive: 4.0.7
  image: ^4.7.2
  cupertino_icons: ^1.0.8
  # Ajout des outils pour la base de données
  http: ^1.1.0
  sqflite: ^2.3.0
  path: ^1.8.3
  path_provider: ^2.1.0
  just_audio: ^0.9.36
  audio_session: ^0.1.18
  asset_delivery: ^1.0.0

dev_dependencies:
  flutter_launcher_icons: 0.14.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0 # Version standard stable

# Configuration pour générer l'icône
flutter_icons:
  android: true
  ios: false        # pour l'instant, tu n'as pas besoin d'iOS
  image_path: "assets/icon/logo_coran.png"  # chemin vers ton logo carré 512x512
  adaptive_icon_background: "#FFFFFF"  # fond pour adaptive icon Android
  adaptive_icon_foreground: "assets/icon/logo_coran.png"  # même image pour foreground


flutter:
  uses-material-design: true

  # Gestion des images et fichiers de données
  assets:
    - assets/data/
    - assets/data/ayahinfo_1120.db
    - assets/assetpacks/quran_pages.zip
    - assets/screenshots/
    - assets/fonts/

  # Configuration des polices de caractères
  fonts:
    - family: UthmanicHafs
      fonts:
        - asset: assets/fonts/hafs.ttf
    - family: UthmanicWarsh
      fonts:
        - asset: assets/fonts/warsh.ttf
    - family: UthmanicSousi
      fonts:
        - asset: assets/fonts/sousi.ttf
    - family: UthmanicShouba
      fonts:
        - asset: assets/fonts/shouba.ttf
    - family: UthmanicQaloon
      fonts:
        - asset: assets/fonts/qaloon.ttf
    - family: UthmanicDoori
      fonts:
        - asset: assets/fonts/doori.ttf
    - family: UthmanicBazzi
      fonts:
        - asset: assets/fonts/bazzi.ttf
    - family: UthmanicQumbul
      fonts:
        - asset: assets/fonts/qumbul.ttf